// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTbGT33axm97YTh22wGlUKObkt5ogM4k',
    appId: '1:243813647884:web:cc924b20bbeef93d64d029',
    messagingSenderId: '243813647884',
    projectId: 'smart-gsr',
    authDomain: 'smart-gsr.firebaseapp.com',
    databaseURL: 'https://smart-gsr-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gsr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkIvdGExcfxE56trZ_ns-jH9rShQSQ_h4',
    appId: '1:243813647884:android:85ead6a99c3d45c164d029',
    messagingSenderId: '243813647884',
    projectId: 'smart-gsr',
    databaseURL: 'https://smart-gsr-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gsr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHL6jexeAt19HQwqpcEIhiVCHsA-vIo_g',
    appId: '1:243813647884:ios:206be80473e3228e64d029',
    messagingSenderId: '243813647884',
    projectId: 'smart-gsr',
    databaseURL: 'https://smart-gsr-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gsr.firebasestorage.app',
    iosBundleId: 'com.example.sdrcClasses',
  );
}
